@baseurl = {{$dotenv BASE_URL}}
@testurl = {{$dotenv BASE_URL}}/api/user/test
@signupurl = {{$dotenv BASE_URL}}/api/auth/signup
@signinurl = {{$dotenv BASE_URL}}/api/auth/signin
@updateinurl = {{$dotenv BASE_URL}}/api/user/update/65907695dc131054e1ae2b46
@deleteurl = {{$dotenv BASE_URL}}/api/user/delete/65907695dc131054e1ae2b46
@signouturl = {{$dotenv BASE_URL}}/api/auth/signout
@createListing = {{$dotenv BASE_URL}}/api/listing/createListing
@userlistingurl= {{$dotenv BASE_URL}}/api/user/listings/65907695dc131054e1ae2b46
### GET baseurl
GET {{testurl}}

### POST auth
POST {{signupurl}}/
Content-Type: application/json

{
    "username": "testing",
    "email": "testing",
    "password": "testing"
}

### POST auth
POST {{signinurl}}
Content-Type: application/json

{
    "email": "testing@gmail.com",
    "password": "testing"
}

### Update 
POST {{updateinurl}}
Content-Type: application/json

{
    "password": "test"
}

### DElete
DELETE {{deleteurl}}

### SignOut
GET {{signouturl}} 

### POST
POST {{createListing}}
Content-Type: application/json

{
    "name": "test",
    "description": "test",
    "address": "test",
    "regularPrice": 500,
    "discountPrice": 500,
    "bathrooms": 5,
    "bedrooms": 5,
    "furnished": true,
    "parking": false,
    "type": "rent",
    "offer": true,
    "imageUrl": ["adfs","asdf"],
    "userRef": "65907695dc131054e1ae2b46"
}
### GET USERLISTINGS
GET {{userlistingurl}} 